name: Release and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  release:
     uses: GY-CODING/.github/.github/workflows/auto-release.yml@master
     secrets: inherit
  deploy:
     uses: GY-CODING/.github/.github/workflows/next-deploy.yml@master
     secrets: inherit
     with: 
       domain: "<subdomain>.gycoding.com"
