name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *" # Ejecutar diariamente (puedes ajustar este cron)
  workflow_dispatch: # Permite ejecutar manualmente el workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checar el código del repositorio
      - name: Checkout Fork
        uses: actions/checkout@v3

      # Step 2: Configurar el remoto upstream
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/GY-CODING/<repository-name>.git
          git fetch upstream

      # Step 3: Sincronizar cambios de la rama principal
      - name: Merge changes from upstream/master
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
